ALTER TABLE "events"
ADD COLUMN "view_count" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "articles"
ADD COLUMN "view_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "download_count" INTEGER NOT NULL DEFAULT 0;
