export const institutionalAreas = [
  "Saúde",
  "Tecnologia e Computação",
  "Engenharias",
  "Ciências Agrárias",
  "Arquitetura, Design e Criatividade",
  "Gestão, Negócios e Administração",
  "Direito e Ciências Humanas",
  "Educação e Licenciaturas",
] as const;

export const institutionalCourses = [
  "Biomedicina",
  "Enfermagem",
  "Farmácia",
  "Fisioterapia",
  "Nutrição",
  "Psicologia",
  "Odontologia",
  "Engenharia Civil",
  "Engenharia da Computação",
  "Engenharia Mecânica",
  "Ciência da Computação",
  "Análise e Desenvolvimento de Sistemas",
  "Sistemas de Informação",
  "Administração",
  "Ciências Contábeis",
  "Gestão de Recursos Humanos",
  "Gestão Financeira",
  "Marketing",
  "Logística",
  "Direito",
  "Pedagogia",
  "Arquitetura e Urbanismo",
  "Design Gráfico",
  "Agronomia",
  "Medicina Veterinária",
  "Estética",
] as const;
